#!/usr/bin/env ruby
require "rubygems"
require "bundler/setup"
require "mailman"

Mailman.config.pop3 = {
  server: 'pop.gmail.com', port: 995, ssl: true,
  username: "none",
  password: "none"
}

Mailman::Application.run do
  default do
    Ticket.receive_mail(message)
  end
end
